ontrack-2305/ontrack_be

- Gemfile.lock
- README.md
README DRAFT
- [100] SimpleCov test percentage
> feat: adding readme first draft

- README.md
Small updates to the readme. Added logo
- [100] SimpleCov test percentage
> Nick readme draft

- app/controllers/api/v1/breakdowns_controller.rb
- config/routes.rb
- spec/fixtures/vcr_cassettes/Chat_Service_API/Chat_service/happy_path/chat_service_task_breakdown.yml
- spec/fixtures/vcr_cassettes/Holiday_Service_API/Holiday_service/happy_path/holiday_service_returns_next_three_holidays.yml
- spec/fixtures/vcr_cassettes/Holiday_Service_API/Holiday_service/holiday_service_returns_next_three_holidays/happy_path.yml
- spec/fixtures/vcr_cassettes/HolidaysSerializer/_as_json/returns_the_correct_JSON_structure.yml
- spec/requests/api/v1/chat_service_request_spec.rb
- spec/requests/api/v1/holidays_request_spec.rb
- spec/serializers/holiday_serializer_spec.rb
Up to date testing and sad path for breakdowns controller
sad path for breakdowns controller
> feat: Sad path for breakdowns controller and up to date testing

- .circleci/config.yml
- Gemfile.lock
- Procfile
Setup CircleCI and deploy to Heroku
> Circleci setup

- app/controllers/api/v1/tasks_controller.rb
- app/models/task.rb
- spec/factories/tasks.rb
- spec/models/task_spec.rb
- spec/requests/api/v1/tasks_request_spec.rb
Revise response body in TaskController to include only status and custom success message
improves UX for all Task CRUD
> Add success messaging

- app/controllers/api/v1/tasks_controller.rb
- app/serializers/error_serializer.rb
- environment.rb
- spec/requests/api/v1/chat_service_request_spec.rb
- spec/requests/api/v1/tasks_request_spec.rb
Edit error serializer so the JSON response matches the contract; edit task and chat request specs to reflect changes.
error messaging for CRUD
> Edit Error Response and Corresponding Tests

- app/controllers/api/v1/tasks_controller.rb
- app/facades/tasks_facade.rb
- spec/facades/tasks_facade_spec.rb
- spec/requests/api/v1/tasks_request_spec.rb
- spec/serializers/task_serializer_spec.rb
Implement a filter using AR queries check for hidden params so that the index page can filter tasks via same index endpoint
Filter buttons on Task Index Page
> Filter index

- app/controllers/api/v1/tasks_controller.rb
- app/models/task.rb
- config/routes.rb
- db/migrate/20230917042752_add_completed_to_tasks.rb
- db/schema.rb
- spec/models/task_spec.rb
- spec/requests/api/v1/tasks_request_spec.rb
Add in algorithm and endpoint for daily tasks
As per our discussion I will revise this algorithm to prompt users to do mandatory tasks first
- [95%] SimpleCov test percentage
> Daily tasks algorithms

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/google_calendar_controller.rb
- app/controllers/api/v1/tasks_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/facades/calendar_events_facade.rb
- app/models/task.rb
- app/poros/calendar_event.rb
- app/poros/user.rb
- app/serializers/calendar_events_serializer.rb
- app/serializers/task_serializer.rb
- app/services/google_calendar_service.rb
- config/routes.rb
- db/migrate/20230919215939_add_skipped_to_tasks.rb
- db/schema.rb
- spec/requests/api/v1/tasks_request_spec.rb
Updated daily_task algorithm
Built in functionality for skipped
Added mandatory tasks to come first in daily_tasks array
Google calendar API consumption / Request service for FE
Biggest notable feature is google calendar API consumption and repackaging for FE
- [95%] SimpleCov test percentage
> Calendar play

- app/models/task.rb
added guard clause if event_date is nil
- [95%] SimpleCov test percentage
> fix: Add guard clause to same_date? method

- app/controllers/api/v1/tasks_controller.rb
- [] Entire test suite is passing
- [] SimpleCov test percentage
> wip: AWS functionality

- app/controllers/api/v1/tasks_controller.rb
- app/serializers/task_serializer.rb
- db/migrate/20230920181441_add_image_column_to_tasks_table.rb
- db/schema.rb
- [] Entire test suite is passing
- [] SimpleCov test percentage
> wip: AWS work

- app/controllers/api/v1/tasks_controller.rb
- spec/requests/api/v1/tasks_request_spec.rb
- [] Entire test suite is passing
- [] SimpleCov test percentage
> Aws reception

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/users_controller.rb
- app/models/task.rb
- config/application.rb
- spec/factories/tasks.rb
- spec/fixtures/vcr_cassettes/Chat_Service_API/Chat_service/happy_path/chat_service_task_breakdown.yml
- spec/fixtures/vcr_cassettes/Holiday_Service_API/Holiday_service/happy_path/holiday_service_returns_next_three_holidays.yml
- spec/fixtures/vcr_cassettes/HolidaysSerializer/_as_json/returns_the_correct_JSON_structure.yml
- spec/models/task_spec.rb
- spec/poros/calendar_event_spec.rb
- spec/poros/error_message_spec.rb
- spec/poros/user_spec.rb
- spec/rails_helper.rb
- spec/requests/api/v1/chat_service_request_spec.rb
- spec/requests/api/v1/holidays_request_spec.rb
- spec/requests/api/v1/tasks_request_spec.rb
- spec/serializers/calendar_event_serializer_spec.rb
- spec/serializers/error_serializer_spec.rb
- spec/serializers/holiday_serializer_spec.rb
- spec/services/google_calendar_service_spec.rb
- spec/services/holidays_service_spec.rb
- spec/sidekiq/reset_skipped_tasks_spec.rb
Where tests were hardcoded with time-sensitive data (ex, returning the next three holidays) tests were changed to be dynamic so they still pass over time
Added extra lines in some tests to prove other aspects of functionality (ex, that all tasks returned by certain methods belong to only one user)
Removed all examples of `if tasks_by_category[category].any?` from Task model, which caused the last event in every category to not be put in the daily tasks array. 
Finished testing all Task model methods
Created new test files (mainly poros and serializers)
All features. This branch focuses on creating tests for features that were not tested yet, and bulking up existing tests for other features.
- [99.14%] SimpleCov test percentage
> Testing testing one two three

- README.md
- [90+] SimpleCov test percentage
PR contains updates to readme. Added equity analysis, added additional json contract responses, updated future ideas for improvement, fix the logo.
LET ME KNOW IF I SHOULD ADD ANYTHING ELSE PLZ :)
> dem readme changes yo

- README.md
- app/controllers/api/v1/tasks_controller.rb
- app/models/task.rb
- app/serializers/task_serializer.rb
- spec/fixtures/vcr_cassettes/AiResponseFacade/class_methods/returns_a_breakdown_object.yml
- spec/fixtures/vcr_cassettes/AiService/instance_methods/_fetch_gpt_response/returns_a_response_from_openai_s_api.yml
- spec/fixtures/vcr_cassettes/Chat_Service_API/Chat_service/happy_path/chat_service_task_breakdown.yml
- spec/fixtures/vcr_cassettes/Holiday_Service_API/Holiday_service/happy_path/holiday_service_returns_next_three_holidays.yml
- spec/fixtures/vcr_cassettes/HolidaysFacade/returns_upcoming_holidays.yml
- spec/fixtures/vcr_cassettes/HolidaysSerializer/_as_json/returns_the_correct_JSON_structure.yml
- spec/fixtures/vcr_cassettes/HolidaysService/connects_to_the_api_and_returns_upcoming_holidays.yml
- spec/models/task_spec.rb
- spec/requests/api/v1/tasks_request_spec.rb
Removes time_needed as a mandatory attribute and removes it from the JSON response,
but keeps functionality for creating tasks with time_needed fields, if that should ever be desired.
> Time needed updates

- README.md
Adds note to README regarding the time_needed attribute and what it could potentially be used for in the future.
> Add note about time_needed future ideas

- config/cable.yml
Add config variables to get action cable to work in deployment
> Actioncable

- config/environments/production.rb
- config/routes.rb
> wip: deployment

- config/cable.yml
- config/environments/production.rb
> wip: It's an origin problem so I am tailoring origins accordingly

- config/environments/production.rb
remove the heightened logging for actioncable as that broke the cable
> fix: remove a config.log_level that broke the cable

- config/cable.yml
add proper origins for deployed FE to action cable
> fix: Add appropriate origins for deployed FE to connect to cable
